name: final_projesi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  file_picker: ^8.1.6
  firebase_storage: ^12.3.7
  googleapis: ^13.2.0
  googleapis_auth: ^1.5.0
  google_sign_in: ^6.2.0
  http: ^1.2.2
  url_launcher: ^6.1.7
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.3.6
  shared_preferences: ^2.1.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - .env


